### ISSUE TITLE
sql export

### ISSUE THREAD

**Issue by gregtampa** [rgajendran/ctf_marker#7]
can you do a mysel export of the database tables?

**Comment by rgajendran** [comment]
As of now there is no option to export mysql database. Soon there will be an option to export database using admin account.

**Comment by gregtampa** [comment]
I figured out how to create the database thanks.
Whats the defualt admin password: 2722e43f2d69d11363dd048e69319dcf  is the hash..

**Comment by gregtampa** [comment]
$hash = md5($password . "CTF");  guess i can generate one and replace it in db

**Comment by rgajendran** [comment]
Soon I will update the installation procedure on the **README file.**. For now,
1) clone entire project using git **https://github.com/rgajendran/ctf_marker.git**
2) Update **template/connection.php** file with your database detail.
3) Directly navigate to **yourdomain/admin.php** page on the browser.(You dont need the password for the first time)
4) Once you login, you can create all the necessary tables in a click using **Database Management Tab**  
5) Once you create tables, it will automatically close the session and redirects you to index.php
6) Later you can use default login details (Username : admin && Password : admin)
