### ISSUE TITLE
Map Not Initialised

### ISSUE THREAD

**Issue by gregtampa** [rgajendran/ctf_marker#9]
Map Not Initialised error in main.php

**Comment by rgajendran** [comment]
Once you setup all tables in admin account.
1) **Create Teams**
2) **Choose number of players per team and create team logins** (You can generate tokens and give it to the users to register in index.php page or you can directly generate usernames & passwords and give it to the users directly to login)
3) Generate [SecGen](https://github.com/cliffe/SecGen/blob/master/scenarios/ctf/flawed_fortress_1.xml) Challenge and import **marker.xml** file in **Import SecGen** tab. (You will have 2 options, you can import same challenges to all the created teams or you can manually import separate challenges to individual teams)
4) According to the challenges, Map will be Initialised for the users and team.
